---
- name: Stop Apigee Service
  command: 'removes=/opt/apigee/apigee-service /opt/apigee/apigee-service/bin/apigee-service {{apigee_service}}  stop'
  
- name: Uninstall Apigee Service
  command: 'removes=/opt/apigee/apigee-service /opt/apigee/apigee-service/bin/apigee-service {{apigee_service}} uninstall'
